
spring:
  application:
      name: myfilter
  profiles:
    active: dev
#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret



server:
  port: 10000
  servlet:
    context-path: /


