
spring:
  application:
      name: springboot-log-mdc
#  profiles:
#    active: test


#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret


server:
  port: 10013
#  servlet:
#    context-path: /

author: admin


logging:
  file:
    name: springboot-mdc-log
    path:


