
spring:
  application:
      name: startupfailure
#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret



server:
  port: 10001
  servlet:
    context-path: /
  address: 192.168.6.170
#    context-path: /producer


logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      kq: DEBUG

