
spring:
  application:
      name: jetcache

server:
  port: 10001
  servlet:
    context-path: /
  address: localhost
#  address: 192.168.6.170
#    context-path: /producer

jetcache:
  statIntervalMinutes: 15
    areaInCacheName: false
    local:
      default:
        type: linkedhashmap # 已支持可选：linkedhashmap、caffeine
        keyConvertor: fastjson
#    remote:
#      default:
#        type: redis
#        keyConvertor: fastjson
#        valueEncoder: java
#        valueDecoder: java
#        poolConfig:
#          minIdle: 5
#          maxIdle: 20
#          maxTotal: 50
#        host: 127.0.0.1
#        port: 6379


logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      kq: DEBUG

