
server:
  port: 10002
  servlet:
    context-path: /

spring:
  application:
    name: mybatis-mapper
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
      connection-timeout: 20000  # 20s
      pool-name: hikari-pool
      leak-detection-threshold: 5000
      minimum-idle: 2
      maximum-pool-size: 5
#      leak-detection-threshold: 180000
#      jdbc-url: jdbc:mysql://192.168.5.212:8066/testdb?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:com/kq/mybatis/mapper/*.xml
