
spring:
  application:
      name: activemq-producer
  activemq:
    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret



server:
  port: 18090
  servlet:
    context-path: /
#    context-path: /producer
