
spring:
  application:
      name: springboot-logback
  profiles:
    active: test


#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret


server:
  port: 10012
  servlet:
    context-path: /

author: admin


logging:
  file:
    name: springboot-logback-log
    path: c:\\logs


