
spring:
  application:
      name: springboot-conditional

#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret



server:
  port: 10016
  servlet:
    context-path: /



