
spring:
  application:
      name: activemq-producer
  profiles:
    active: dev
#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret



server:
  port: 10000
  servlet:
    context-path: /
  address: localhost
#  address: 192.168.6.170
#    context-path: /producer

abc: 1

my:
  name: 170
  port: 12000
  username: root
  servers:
    - localhost
    - www.kq.com
  map:
      "[/key1]": value1
      "[/key2]": value2
      /key3: value3
      name: king


saleperiod:
  relation:
    huayun: # 左边:华云营业时段  右边:餐厅营业时段
      1: 5
      2: 6
      3: 7
      4: 8



logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      kq: DEBUG

