
spring:
  application:
      name: activemq-producer
#  activemq:
#    broker-url: tcp://mq.server1.com:61616
    #user: admin
    #password: secret



server:
  port: 10000
  servlet:
    context-path: /
  address: 192.168.6.170
#    context-path: /producer

abc: 1

my:
  name: 170
  port: 12000
  username: root


logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      kq: DEBUG

