
server:
  port: 10005


#management: #开启SpringBoot Admin的监控
#  endpoints:
#    promethus:
#      enable: true
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
