

server:
  port: 10001
  servlet:
    context-path: /elasticsearch
  address: localhost

spring:
  application:
    name: elasticsearch
  datasource:
#    url: jdbc:oracle:thin:@192.168.5.248:1521:zhjkctdb
    url: jdbc:oracle:thin:@172.16.7.54:1521:zhjkctdb
    driver-class-name: oracle.jdbc.OracleDriver
    username: xn0731
    password: xn0731
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000  # 20s
      pool-name: hikari-pool
  #      jdbc-url: jdbc:mysql://192.168.5.212:8066/testdb?useUnicode=true&characterEncoding=UTF-8
  #      username: root
  #      password: 123456
  #      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  executor-type: SIMPLE
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: oracle
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      zyxk: debug

my:
  elasticsearch:
    servers:
      - { hostname: "172.16.5.1",port: 9200,scheme: "http" }
#      - { hostname: "172.16.5.3",port: 9200,scheme: "http" }
#      - { hostname: "172.16.6.204",port: 9200,scheme: "http" }

